apiVersion: v1
kind: Service
metadata:
  name: radiology-report-service
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: radiology-report
